### ISSUE TITLE
Error in Heroku 'Configure Environment'

### ISSUE THREAD

**Issue by chajas** [culturekings/facebook-messenger-bot-webhook#1]
Getting an error in heroku in the initial build (Configure Env), file seems to  be missing. Should probably be app.js ?

![image](https://cloud.githubusercontent.com/assets/16645033/14517263/21fc1226-0229-11e6-810f-c3afae8551b0.png)

**Comment by evulse** [comment]
Sorry there was a naming issue. I've updated plus added some other new features such as making the application an echo bot by default so that it is easier to see it working and see how it works.
